collection @sites

attributes :id,
          :case_number,
          :name,
          :address,
          :latitude,
          :longitude,
          :blurred_latitude,
          :blurred_longitude,
          :city,
          :county,
          :state,
          :zip_code,
          :org_name,
          :work_type,
          :status,
          :work_requested,
          :claimed_by,
          :data,
          :request_date